name:                Hox
version:             0.1.0.0
github:              "githubuser/Hox"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Hox#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers >= 0.6 && < 0.7
- dates
- http-client
- http-client-tls
- http-conduit
- lens >= 4.7 && < 5
- mtl
- network-uri
- parsec
- reflex
  # - reflex-gi-gtk
- reflex-vty
- text
- uri-encode
- uuid
- vector
- yaml
  # - reflex-dom-core

library:
  source-dirs: src

executables:
  Hox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hox

tests:
  Hox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hox
